[20735] bump solrj version to 6.4.1
Since the old version pulls in an old version of apache httpclient which
causes the same problems fixed in 110190 (NoSuchMethodError at runtime).


git-svn-id: https://svn.dbc.dk/repos/dataio/trunk@110208 b87a6194-a221-0410-ad6f-3b8ec35bba13